// components/SnsList.vue
<template>
  <div class="contact_follow_wrap">
    <p class="ttl">Contact &amp; Follow</p>
    <ul class="columns is-mobile">
      <li class="column">
        <p class="contanc_item">
          <a href="https://twitter.com/ishiyamayuichi" target="_blank" rel="noopener"><img loading="lazy" src="~assets/img/Twitter.png" alt="Twitter" width="40" height="40"></a>
        </p>
      </li>
      <li class="column">
        <p class="contanc_item">
          <a href="https://github.com/yufrom" target="_blank" rel="noopener"><img loading="lazy" src="~assets/img/Github.png" alt="Github" width="40" height="40"></a>
        </p>
      </li>
      <li class="column">
        <p class="contanc_item">
          <a href="https://www.pinterest.jp/yu123daa/" target="_blank" rel="noopener"><img loading="lazy" src="~assets/img/Pinterest.png" alt="Pinterest" width="40" height="40"></a>
        </p>
      </li>
      <li class="column">
        <p class="contanc_item">
          <a href="mailto:fromscratch.yi@gmail.com?subject=Contact-to-FromScratch"><img loading="lazy" src="~assets/img/Mail.png" alt="Mail" width="40" height="40"></a>
        </p>
      </li>
    </ul>
  </div>
</template>

<style lang="scss" scoped>
.contact_follow_wrap {
  max-width: 250px;
  margin: 0 auto;
  .ttl {
    margin: 0 0 10px;
    font-size: 1.1em;
    font-weight: bold;
    text-align: center;
  }
  .contact_item {
    text-align: center;
  }
}
</style>

// src/components/snsList.tsx
import Image from 'next/image';
import Link from 'next/link';
import styles from 'styles/components/SnsList.module.scss';
const SnsList = (): JSX.Element => {
  return (
    <section className={styles.sns_list_wrap}>
      <h2>Contact &amp; Follow</h2>
      <ul>
        <li>
          <Link href="https://twitter.com/ishiyamayuichi" passHref>
            <a target="_blank" rel="noopener">
              <Image
                priority={true}
                width={40}
                height={40}
                src="/images/ico_twitter.png"
                alt="Twitter"
              />
            </a>
          </Link>
        </li>
        <li>
          <Link href="https://github.com/yufrom" passHref>
            <a target="_blank" rel="noopener">
              <Image
                priority={true}
                width={40}
                height={40}
                src="/images/ico_github.png"
                alt="Twitter"
              />
            </a>
          </Link>
        </li>
        <li>
          <Link href="https://www.pinterest.jp/yu123daa/" passHref>
            <a target="_blank" rel="noopener">
              <Image
                priority={true}
                width={40}
                height={40}
                src="/images/ico_pinterest.png"
                alt="Pinterest"
              />
            </a>
          </Link>
        </li>
        <li>
          <Link href="mailto:fromscratch.yi@gmail.com?subject=Contact From Portfolio" passHref>
            <a>
              <Image priority={true} width={40} height={40} src="/images/ico_mail.png" alt="Mail" />
            </a>
          </Link>
        </li>
      </ul>
    </section>
  );
};
export default SnsList;
